apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-systeemtester-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: systeemtester
    repoURL: "https://github.com/johan974/argocd-demo.git"
    branch: master
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
