apiVersion: v1
kind: Service
metadata:
  name: quotes-service
spec:
  ports:
    - name: http
      port: {{.Values.service.internalPort }}
      protocol: TCP
      targetPort: {{.Values.service.internalPort}}
  selector:
    app: {{.Values.appName}}
  type: {{.Values.service.type}}
