apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: K:\A__IntelliJ_projects\sb2-demo\docker-to-kubernetes\kompose-windows-amd64.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: {{.Values.systemtester.name}}
  name: {{.Values.systemtester.name}}
spec:
  ports:
    - name: "8080"
      port: {{.Values.systemtester.service.externalPort}}
      targetPort: {{ .Values.systemtester.service.internalPort }}
  selector:
    io.kompose.service: {{ .Values.systemtester.name }}
  type: LoadBalancer