apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{.Values.bgtsimulator.name}}
  name: {{.Values.bgtsimulator.name}}
spec:
  ports:
    - name: "8090"
      port: {{.Values.bgtsimulator.service.externalPort}}
      targetPort: {{.Values.bgtsimulator.service.internalPort}}
  selector:
    io.kompose.service: {{.Values.bgtsimulator.name}}
status:
  loadBalancer: {}
