apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{.Values.bgtvspdokdoorlevering.name}}
  name: {{.Values.bgtvspdokdoorlevering.name}}
spec:
  ports:
    - name: "8095"
      port: {{.Values.bgtvspdokdoorlevering.service.externalPort}}
      targetPort: {{.Values.bgtvspdokdoorlevering.service.internalPort}}
  selector:
    io.kompose.service: {{.Values.bgtvspdokdoorlevering.name}}
  type: LoadBalancer

