apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  name: {{ .Values.geocachedetectiveviewer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  strategy: {}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        io.kompose.network/devhome-default: "true"
        io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
    spec:
      containers:
        - name: {{ .Values.geocachedetectiveviewer.name }}
          image: {{ .Values.geocachedetectiveviewer.image.fulldigest5 }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.geocachedetectiveviewer.service.externalPort }}
            - name: https
              containerPort: {{ .Values.geocachedetectiveviewer.service.externalSecurePort }}
          resources: {}
          # mount the TLS cert/key
          {{- if .Values.tls.enabled }}
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/nginx/ssl
              readOnly: true
          {{- end }}
      {{- if .Values.tls.enabled }}
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Values.tls.frontendSecretName }}
      {{- end }}
      restartPolicy: Always
