apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      nodePort: 30036
    - name: "9001"
      port: 9001
      targetPort: 9001
      nodePort: 30037
  selector:
    name: minio
  type: LoadBalancer
