apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-account
                  key: adminname
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-account
                  key: adminpassword
          name: minio
          image: minio/minio
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9001
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-volume
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: minio-volume
          hostPath:
            path: /run/desktop/mnt/host/g/data/minionfs2
            type: Directory