apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.postgrescrud.name }}
  name: {{ .Values.postgrescrud.name }}
spec:
  ports:
    - name: https
      port: {{ .Values.postgrescrud.service.externalPort }}
      targetPort: {{ .Values.postgrescrud.service.internalPort }}
  selector:
    io.kompose.service: {{ .Values.postgrescrud.name }}
  type: LoadBalancer