apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.springbootadmin.name}}
  name: {{.Values.springbootadmin.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.springbootadmin.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.springbootadmin.name}}
    spec:
      containers:
        - env:
            - name: spring.application.name
              value: "{{.Values.springbootadmin.name}}"
            - name: server.port
              value: "{{.Values.springbootadmin.port}}"
          image: "solvedshared/{{.Values.springbootadmin.name -}}:{{- .Values.springbootadmin.version}}"
          name: {{.Values.springbootadmin.name}}
          ports:
            - containerPort: {{.Values.springbootadmin.port}}
      restartPolicy: Always
# 
# 
# 
## 
