apiVersion: v1
kind: Service
metadata:
  name: {{.Values.springbootadmin.name}}
  labels:
    app: {{.Values.springbootadmin.name}}
spec:
  ports:
    - name: "sbadmin-port"
      port: {{.Values.springbootadmin.port}}
      protocol: TCP
      targetPort: {{.Values.springbootadmin.port}}
  selector:
    app: {{.Values.springbootadmin.name}}
  type: LoadBalancer
