apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Values.systemtesterviewer.name }}
  name: {{ .Values.systemtesterviewer.name }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.systemtesterviewer.service.externalPort }}
      targetPort: {{ .Values.systemtesterviewer.service.internalPort }}
  selector:
    io.kompose.service: {{ .Values.systemtesterviewer.name }}
  type: LoadBalancer