apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo1-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: systemtest
    repoURL: "https://github.com/johan974/quotes.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
