apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: quotes
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          image: solvedshared/quotes:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIR_VAR1
              value: "a-value"
          ports:
            - containerPort: 8080
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 55
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 5
