apiVersion: v1
kind: Service
metadata:
  name: sb2demo-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sb2demo
  type: LoadBalancer
