# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:0b8a13ffe6bf701a0999fc0737a18ed7944e144b49dcbac5fcadf795d9ef9988
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:cb880c749cca5c66fbcb49095912b0972d4a80c33aa0edad69b42dd78f5972f9
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:c7c647aa906641e95c11bee59061967dba5f4a8bfd94d07f9573e7ecbcfebdce
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910