# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:3851090f050a25261c73434bfc6ae772e729384be1cce67eec3266a19af58978
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:eeba9f1ea770c74f884e72eddd1cf49e6552e36e9a897085e6f7d3f93196b726
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:d657c80b30d8c2961d3b2fe91615b372f840e948cd50f2526edb61a9d4996566
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910