# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:d7de8d74f065ad2081780909595f239b1cc5cf7e93e6893c7836241a7428bb93
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:a6113042cd6ebc769133f4303c044db3d86ebf1837db60f49e4ca078fbaabbfa
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:f7f657c0ee30bcf4a77e06618f3480a76ae44c67c1aaf9584f21b4f603446288
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910