# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:b6aa06816d10fa9f1a9226ca1f62827e478a9341352d44beebd0036212b92475
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:92dd9ec64ff0fb9693fc2e12580cec99473c49dc2ed90fda1fe5c9d49b089a3d
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:8252889fe11a63e89aadc6f51410dc6e7320217a2d1e284d92e61af36444ce09
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

systemtesterviewer:
  name: systemtesterviewer
  image:
    fulldigest4: solvedshared/systemtesterviewer@sha256:df6c86295240b1e883684f544fd223018f1c25bd6cdb43111191e9af6f7fddb3
    version: v20241221
  service:
    type: LoadBalancer
    internalPort: 80
    externalPort: 7777

geocachedetectiveviewer:
  name: geocachedetectiveviewer
  image:
    fulldigest5: solvedshared/geocachedetectiveviewer@sha256:0756617dc27490e631f784b9a71f9609a17121a21621d473fbcb6e724e8e696e
    version: v20250416
  service:
    type: LoadBalancer
    internalPort: 443
    externalPort: 8843

geocachedetectiveapi:
  name: geocachedetectiveapi
  image:
    fulldigest6: solvedshared/geocachedetectiveapi@sha256:67c4bc2d3f6d87d5f4848316dc5e1181c691ba2368c73116a4993cdfdf6883f2
    version: v20250416
  service:
    type: LoadBalancer
    internalPort: 8777
    externalPort: 8777

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910

# The SPA frontend will send any request via the nginx proxy to the backend.
#  That means that you don't need https/ssl between the frontend and the backend.
tls:
  enabled: true
  backendEnabled: false
  frontendSecretName: nginx-tls
  backendSecretName: internal-ssl
  backendSecretPasswordKey: keystore-password
  certPath: /etc/nginx/ssl/tls.crt
  keyPath:  /etc/nginx/ssl/tls.key
  keystorePath: /etc/ssl/keystore.p12
  storeType: PKCS12
  keyAlias: tomcat