# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:b6aa06816d10fa9f1a9226ca1f62827e478a9341352d44beebd0036212b92475
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:92dd9ec64ff0fb9693fc2e12580cec99473c49dc2ed90fda1fe5c9d49b089a3d
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:8252889fe11a63e89aadc6f51410dc6e7320217a2d1e284d92e61af36444ce09
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

systemtesterviewer:
  name: systemtesterviewer
  image:
    fulldigest4: solvedshared/systemtesterviewer@sha256:df6c86295240b1e883684f544fd223018f1c25bd6cdb43111191e9af6f7fddb3
    version: v20241221
  service:
    type: LoadBalancer
    internalPort: 80
    externalPort: 7777

geocachedetectiveviewer:
  name: geocachedetectiveviewer
  image:
    fulldigest5: solvedshared/geocachedetectiveviewer@sha256:9fd4afdef3c75a66fd671ab9826b4616cd067d857879d2974270a1e4c6a34fdf
    version: v20250416
  service:
    type: LoadBalancer
    internalPort: 443
    externalPort: 8843

geocachedetectiveapi:
  name: geocachedetectiveapi
  image:
    fulldigest6: solvedshared/geocachedetectiveapi@sha256:76a2ad4c528237c3ed22d706f4e8fff8fb2f03bdc5d23ecc15ae5ac2fc13cfc6
    version: v20250416
  service:
    type: LoadBalancer
    internalPort: 8443
    externalPort: 8443

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910

tls:
  enabled: true
  frontendSecretName: nginx-tls
  backendSecretName: internal-ssl
  backendSecretPasswordKey: keystore-password
  certPath: /etc/nginx/ssl/tls.crt
  keyPath:  /etc/nginx/ssl/tls.key
  keystorePath: /etc/ssl/keystore.p12
  storeType: PKCS12
  keyAlias: tomcat