# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:b2198634f5b2e058a28398c2f25cebb1fcf879f31f4460a71e7ac01d89e2f956
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:d40c4b40e2ba4e3dc5d6c2456de2e2418bd3b454dc72136b6c66898edc491da4
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:657c9441f45fdf1bb6c3dce9a4c23869eca72ce4d186d76428adc0fcfc96c8dd
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910