# Default values for helmconfig.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: systemtester

replicaCount: 1

systemtester:
  name: bgtloadtester
  image:
    fulldigest1: solvedshared/bgtloadtester@sha256:587bedfd1901e3c06b2e6811a001086afaf316b1e879b54d151e70433a0b490a
    version: v20240907
  service:
    type: LoadBalancer
    internalPort: 8080
    externalPort: 8080

bgtsimulator:
  name: bgtsimulator
  image:
    fulldigest2: solvedshared/bgtsimulator@sha256:b0b774dd38d967925c463a0378bac22f0be2dc0b85be6d5b24ab06bee62a37ab
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8090
    externalPort: 8090

bgtvspdokdoorlevering:
  name: bgtvspdokdelivery
  image:
    fulldigest3: solvedshared/bgtvspdokdelivery@sha256:61f0f0d72bcbbd58605722f44987a5e755c0e1cdd46895939a9104e1b0e7ca07
    version: v1
  service:
    type: LoadBalancer
    internalPort: 8095
    externalPort: 8095

springbootadmin:
  name: sbadmin
  port: 8099
  version: v20240910
